server:
  port: 8081
  name: mall-manage-web  
      
#dubbo用的这里的配置      
dubbo:
  application:
    name: mall-manage-web
  protocol:       
    name: dubbo        #dubbo通讯协议名称
  registry:
    address: zookeeper://127.0.0.1:2181     #zk注册中心地址
    protocol: zookeeper    #zk通信协议名称
  base-package: com.maj.mall   #dubbo服务扫描的路径；这样写，避免以后路径不一样，访问不到       

spring:
  thymeleaf:
    cache: false  # 热部署，关闭thymeleaf缓存
    mode: LBGACYHTML5  # 松校验（不需要thymeleaf语法太严格，继承html校验规则）