server:
  port: 7085
  name: mall-passport-web  
      
#dubbo用的这里的配置      
dubbo:
  application:
    name: mall-passport-web
  protocol:       
    name: dubbo        #dubbo通讯协议名称
  registry:
    address: zookeeper://127.0.0.1:2181     #zk注册中心地址
    protocol: zookeeper    #zk通信协议名称
  base-package: com.maj.mall   #dubbo服务扫描的路径；这样写，避免以后路径不一样，访问不到       
  
#  dubbo.protocal.port: #配置dubbo端口号，Dubbo服务之间相互通信的端口号，如果设置了，则可能会出现一台机器仅能启动一个Dubbo服务了，再启动会端口占用
# 需要配置20880，20881，20882
spring:
  thymeleaf:
    cache: false  # 热部署，关闭thymeleaf缓存
    mode: LBGACYHTML5  # 松校验（不需要thymeleaf语法太严格，继承html校验规则）
#  mvc:
#    static-path-pattern: /static/** # 配置静态资源的映射路径，配置的话默认静态资源默认是映射到“/**”

#jwt 的key
config:
  jwt:
    key: 2019gmall110105
  vb:
    url: https://api.weibo.com/
    mallapp:
      key: 361068148
      secret: c8bf5890b49aebc8a065e66e7373bae5